apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-deploy
spec:
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxSurge: "50%"
      #maxUnavailable
  minReadySeconds: 10 # hardcoding the time in seconds the app takes to become available
  selector:
    matchLabels:
      app: my-service
  replicas: 3
  template:
    metadata:
      labels:
        app:  my-service
    spec:
      containers:
      - name: my-service
        image: vinsdocker/k8s-app:v1
        env:
        - name: "key"
          value: "value"
