apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 5
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 2
            memory: 100Mi
          limits:
            cpu: 2
            memory: 100Mi
