version: "3.0"
services:
  mongo:
    image: mongo:4.4-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
    - ./data:/docker-entrypoint-initdb.d 
  express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    depends_on:
    - mongo
    ports:
    - "8081:8081" 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo