apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: {{ .Values.replicaCount }}
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      # . is to tell variable path in the named template, . means the variables in webAppImage start from .Values, mainly we use .
      # inplace of template, we could have used include as well, both are used to import named template
      # in include, we can use it in pipeline but not in template
      # - is added to remove whitespace like new line, which is left after evalution of go expression, fyi result of expression is posted underneath
      {{- include "webAppImage" . | indent 6 }}
---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp
  ports:
    - name: http
      port: 80
      nodePort: 30080
  type: NodePort
