version: "3.0"
services:
  mongo:
    image: mongo:4.4-focal
    volumes:
    - "./data:/docker-entrypoint-initdb.d"
  job-service:
    image: vinsdocker/k8s-dice-job
    depends_on:
    - mongo
    environment:
      spring.data.mongodb.uri: "mongodb://job_user:job_password@mongo:27017/job"
  candidate-service:
    image: vinsdocker/k8s-dice-candidate  
    depends_on:
    - mongo
    - job-service
    environment:
      spring.data.mongodb.uri: "mongodb://candidate_user:candidate_password@mongo:27017/candidate"
      job.service.url: "http://job-service:8080/job/"
  front-end:
    image: vinsdocker/k8s-dice-frontend
    depends_on:
    - candidate-service
    - job-service
  routing-rules:
    image: nginx
    depends_on:
    - candidate-service
    - job-service
    - front-end
    ports:
    - "8080:80"
    volumes:
    - "./conf/nginx.conf:/etc/nginx/nginx.conf" 