apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # would monitor deployment
metadata:
  name: job-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: job-app-deploy # deployment name to monitor
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler # would monitor deployment
metadata:
  name: candidate-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: candidate-app-deploy # deployment name to monitor
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 300


# Install metrics server
