apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: my-app # Route service traffic to pods with label keys and values matching this selector.
  ports:
  - port: 80 # The port that will be exposed by this service.
    targetPort: 80 # Number or name of the port to access on the pods targeted by the service.
