apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: pod-pv-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: pod-pv-volume
    persistentVolumeClaim: # the source is PVC, can be ConfigMap or other
      claimName: my-pvc # linking PVC with pod
