FROM nginx
WORKDIR app
RUN touch live.txt
RUN touch ready.txt

# docker build -t tanishqsaluja/probe-test-image .

# docker push tanishqsaluja/probe-test-image:latest

# kubectl apply -f multiple-probes-exec.yaml

# kubectl delete -f multiple-probes-exec.yaml

# watch -tx kubectl get all

# watch -tx kubectl describe service/my-service