apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy
spec:
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      name: my-pod
      labels:
        app: my-app
    spec:
      containers:
      - name: probe-test-image
        image: tanishqsaluja/probe-test-image
        #startupProbe:
        #  exec:
        #    # we dont have to provide the host endpoint (only path) since kubelet is the one executing these probes so they are on the same host, only thing kubelet expects is the path
        #    command: 
        #    - "cat"
        #    - "live.txt"
        #  # default properties would apply
        #  initialDelaySeconds: 100 # default is 0
        #  periodSeconds: 10 # default is 10 seconds
        #  successThreshold: 1
        #  failureThreshold: 3 # default is 3 as well
        livenessProbe:
          exec:
            command: 
            - "cat"
            - "live.txt"
          initialDelaySeconds: 100 # default is 0
          periodSeconds: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command: 
            - "cat"
            - "ready.txt"       
          initialDelaySeconds: 100 # default is 0
          periodSeconds: 1
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: ClusterIP # Default is ClusterIP
  selector:
    app: my-app # Route service traffic to pods with label keys and values matching this selector.
  ports:
  - port: 80 # The port that will be exposed by this service.
    targetPort: 80 # Number or name of the port to access on the pods targeted by the service.

