apiVersion: v1
kind: Pod
metadata:
  name: pod-assignment
spec:
  restartPolicy: OnFailure
  containers:
  - name: assignment
    image: vinsdocker/k8s-pod-assignment
    args:
    - "MY_ARG"
    env:
    - name: "NUMBER"
      value: "5"
