apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 5
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "sleep"
    - "25"
