apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  otherVar1: "var1"
  otherVar2: "var2"
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1 # Default is 30 seconds
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "otherVar1"
      valueFrom:
        configMapKeyRef:
          name: app-properties
          key: otherVar1
    args:
    - env
