apiVersion: v1
kind: ConfigMap
metadata:
  name: app-properties
data:
  application.properties: |
    appUrl=http://my-service
    timeout=60
  dummy.json: |
    {
      "key1": "value1",
      "key2": "value2"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1 # Default is 30 seconds
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    args:
    - "sleep" # sleep since ubuntu container terminates after starting but we want to exec into it
    - "3600"
    volumeMounts:
    - name: config-volume1
      mountPath: /usr/share/injected-file
  volumes:
  - name: config-volume1
    configMap: # We have Secret, PersistentVolume options as well for Volume
      name: app-properties
