apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  username: VGFuaXNocQ==
  password: U3Ryb25n
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  terminationGracePeriodSeconds: 1 # Default is 30 seconds
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "username"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: username
    - name: "password"
      valueFrom:
        secretKeyRef:
          name: app-secret
          key: password
    args:
    - env
